-- 1. FORCE ADMIN ROLE & FIX PERMISSIONS
SET ROLE postgres;

GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT CREATE ON SCHEMA public TO postgres, service_role;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO service_role;

-- 2. CREATE TABLES

-- Waitlist Table
create table if not exists public.waitlist_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.waitlist_users enable row level security;

-- Partners Table
create table if not exists public.early_partners (
  id bigint generated by default as identity primary key,
  pharmacy_name text,
  owner_name text,
  email text,
  phone text,
  license_no text,
  address text,
  services text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.early_partners enable row level security;

-- Feedback Table
create table if not exists public.feedback_submissions (
  id bigint generated by default as identity primary key,
  role text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.feedback_submissions enable row level security;

-- Survey Table
create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  role text,
  answers jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.survey_responses enable row level security;

-- Community Table
create table if not exists public.saturday_community_members (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.saturday_community_members enable row level security;

-- App Config Table
create table if not exists public.app_config (
  id bigint generated by default as identity primary key,
  app_name text default 'Pharmelo',
  contact_email text default 'hello@pharmelo.com',
  twitter_url text default '#',
  instagram_url text default '#',
  linkedin_url text default '#',
  logo_url text default '',
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.app_config enable row level security;

-- Insert default config (One time setup)
insert into public.app_config (id, app_name, contact_email)
values (1, 'Pharmelo', 'hello@pharmelo.com')
on conflict (id) do nothing;


-- 3. POLICIES

-- Waitlist Policies
drop policy if exists "Public Insert Waitlist" on public.waitlist_users;
create policy "Public Insert Waitlist" on public.waitlist_users for insert with check (true);
drop policy if exists "Admin View Waitlist" on public.waitlist_users;
create policy "Admin View Waitlist" on public.waitlist_users for select using (auth.role() = 'authenticated');

-- Partner Policies
drop policy if exists "Public Insert Partners" on public.early_partners;
create policy "Public Insert Partners" on public.early_partners for insert with check (true);
drop policy if exists "Admin View Partners" on public.early_partners;
create policy "Admin View Partners" on public.early_partners for select using (auth.role() = 'authenticated');

-- Feedback Policies
drop policy if exists "Public Insert Feedback" on public.feedback_submissions;
create policy "Public Insert Feedback" on public.feedback_submissions for insert with check (true);
drop policy if exists "Admin View Feedback" on public.feedback_submissions;
create policy "Admin View Feedback" on public.feedback_submissions for select using (auth.role() = 'authenticated');

-- Survey Policies
drop policy if exists "Public Insert Survey" on public.survey_responses;
create policy "Public Insert Survey" on public.survey_responses for insert with check (true);
drop policy if exists "Admin View Survey" on public.survey_responses;
create policy "Admin View Survey" on public.survey_responses for select using (auth.role() = 'authenticated');

-- Community Policies
drop policy if exists "Public Insert Community" on public.saturday_community_members;
create policy "Public Insert Community" on public.saturday_community_members for insert with check (true);
drop policy if exists "Admin View Community" on public.saturday_community_members;
create policy "Admin View Community" on public.saturday_community_members for select using (auth.role() = 'authenticated');

-- Config Policies
drop policy if exists "Public Read Config" on public.app_config;
create policy "Public Read Config" on public.app_config for select using (true);
drop policy if exists "Admin Update Config" on public.app_config;
create policy "Admin Update Config" on public.app_config for update using (auth.role() = 'authenticated');

-- 4. NOTIFICATIONS SYSTEM

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  type text not null, -- 'info', 'success', 'warning'
  title text not null,
  message text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.admin_notifications enable row level security;

-- Policies
drop policy if exists "Admin Select Notifications" on public.admin_notifications;
create policy "Admin Select Notifications" on public.admin_notifications for select using (auth.role() = 'authenticated');

drop policy if exists "Admin Update Notifications" on public.admin_notifications;
create policy "Admin Update Notifications" on public.admin_notifications for update using (auth.role() = 'authenticated');

drop policy if exists "Public Insert Notifications" on public.admin_notifications;
create policy "Public Insert Notifications" on public.admin_notifications for insert with check (true);

-- 5. SECURE STATS FUNCTION (CRITICAL FOR HERO PAGE)
-- This allows the public page to see the COUNT of users without seeing the emails.

create or replace function public.get_landing_stats()
returns json as $$
declare
  w_count int;
  p_count int;
begin
  select count(*) into w_count from public.waitlist_users;
  select count(*) into p_count from public.early_partners;
  return json_build_object('waitlist', w_count, 'partners', p_count);
end;
$$ language plpgsql security definer;

-- Grant execution to everyone
grant execute on function public.get_landing_stats to anon, authenticated, service_role;


-- 6. REALTIME REPLICATION
begin;
  -- Remove first to avoid duplicates if re-running
  alter publication supabase_realtime drop table if exists public.waitlist_users;
  alter publication supabase_realtime drop table if exists public.early_partners;
  
  -- Add tables
  alter publication supabase_realtime add table public.waitlist_users;
  alter publication supabase_realtime add table public.early_partners;
  alter publication supabase_realtime add table public.feedback_submissions;
  alter publication supabase_realtime add table public.survey_responses;
  alter publication supabase_realtime add table public.admin_notifications;
commit;