-- Run this entire script in your Supabase SQL Editor to fix the saving issues.

-- 1. Create the Feedback Table (if missing)
create table if not exists public.feedback_submissions (
  id bigint generated by default as identity primary key,
  role text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create the Survey Table (if missing)
create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  role text,
  answers jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
alter table public.feedback_submissions enable row level security;
alter table public.survey_responses enable row level security;

-- 4. PERMISSIONS: Allow anyone (including anonymous users) to insert data
-- We drop existing policies first to avoid "policy already exists" errors
drop policy if exists "Public Insert Feedback" on public.feedback_submissions;
create policy "Public Insert Feedback" 
on public.feedback_submissions 
for insert 
to public 
with check (true);

drop policy if exists "Public Insert Survey" on public.survey_responses;
create policy "Public Insert Survey" 
on public.survey_responses 
for insert 
to public 
with check (true);

-- 5. PERMISSIONS: Allow Admins to view the data
drop policy if exists "Admin View Feedback" on public.feedback_submissions;
create policy "Admin View Feedback" 
on public.feedback_submissions 
for select 
to authenticated 
using (true);

drop policy if exists "Admin View Survey" on public.survey_responses;
create policy "Admin View Survey" 
on public.survey_responses 
for select 
to authenticated 
using (true);

-- 6. Explicit Grants (Safety net for API access)
grant insert on public.feedback_submissions to anon, authenticated;
grant insert on public.survey_responses to anon, authenticated;
grant select on public.feedback_submissions to authenticated;
grant select on public.survey_responses to authenticated;